#!/bin/bash
# clasp: gbie1.lp unsat_01.lp is unsatisfiable
# Author: Thomas Krennwallner <tkren@kr.tuwien.ac.at>
# Date: 2017-05-07

set -o pipefail

gringo /usr/share/doc/gringo/examples/gringo/gbie/{gbie1.lp,instances/unsat_01.lp} | clasp

result=$?
test $result -eq 20
